export const initialState = {
  firstname: '',
  lastname: '',
  firstnamePartner: '',
  lastnamePartner: '',
  m1: undefined,
  m2: undefined,
  m3: undefined,
  m4: undefined,
  m5: undefined,
  m6: undefined,
  m7: undefined,
  m8: undefined,
  m9: undefined,
  m10: undefined,
  m11: undefined,
  m12: undefined,
  m13: undefined,
  m14: undefined,
  day: undefined,
  month: undefined,
  year: undefined,
  dayPartner: undefined,
  monthPartner: undefined,
  yearPartner: undefined,
}

export const resetState = {
  firstname: '',
  lastname: '',
  firstnamePartner: '',
  lastnamePartner: '',
  m1: undefined,
  m2: undefined,
  m3: undefined,
  m4: undefined,
  m5: undefined,
  m6: undefined,
  m7: undefined,
  m8: undefined,
  m9: undefined,
  m10: undefined,
  m11: undefined,
  m12: undefined,
  m13: undefined,
  m14: undefined,
  firstSetHouses: [],
  secondSetHouses: [],
  day: undefined,
  month: undefined,
  year: undefined,
  dayPartner: undefined,
  monthPartner: undefined,
  yearPartner: undefined
};